name: Bug 报告
description: 报告可复现的问题
title: '[Bug] '
labels: [bug]
body:
  - type: textarea
    attributes:
      label: 问题描述
    validations:
      required: true
  - type: textarea
    attributes:
      label: 复现步骤
    validations:
      required: true
  - type: input
    attributes:
      label: iOS / iPadOS 版本
    validations:
      required: true
  - type: input
    attributes:
      label: LifeTimer 版本
    validations:
      required: true
  - type: textarea
    attributes:
      label: 补充信息

